#!/bin/bash

# NOTE THIS IS THE ROOT FOR BASELINE SYSTEM
TURBO_ROOT="/home/lingpenk/TBP/TurboParser"

# Use this to create .tagging files first. 
# ./scripts/create_tagging_corpus.sh /home/lingpenk/Data/PTB/PTB_330/train

TAGGING_ROOT="/home/lingpenk/Data/PTB/PTB_330/"
TAGGING_FILE="train.tagging"
CONLL_FILE="train"

WORKING_DIR="/home/lingpenk/Data/PTB/PTB_330/jacktagging/"

mkdir ${WORKING_DIR}

python /home/lingpenk/research/scripts/SplitDataSet.py ${TAGGING_ROOT}${TAGGING_FILE} 10 ${WORKING_DIR}${TAGGING_FILE}

cd ${WORKING_DIR}

cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 > ${WORKING_DIR}${TAGGING_FILE}_no10
cat ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no1
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no2
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no3
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no4
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no5
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no6
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no7
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}9 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no8
cat ${WORKING_DIR}${TAGGING_FILE}1 ${WORKING_DIR}${TAGGING_FILE}2 ${WORKING_DIR}${TAGGING_FILE}3 ${WORKING_DIR}${TAGGING_FILE}4 ${WORKING_DIR}${TAGGING_FILE}5 ${WORKING_DIR}${TAGGING_FILE}6 ${WORKING_DIR}${TAGGING_FILE}7 ${WORKING_DIR}${TAGGING_FILE}8 ${WORKING_DIR}${TAGGING_FILE}10 > ${WORKING_DIR}${TAGGING_FILE}_no9

cd ${TURBO_ROOT}

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd;`/deps/local/lib:"
for i in {1..10}
do 
./TurboTagger --train --file_train=${WORKING_DIR}${TAGGING_FILE}_no$i --file_model=${WORKING_DIR}model_no$i --form_cutoff=1 --logtostderr
./TurboTagger --test --evaluate --file_model=${WORKING_DIR}model_no$i --file_test=${WORKING_DIR}${TAGGING_FILE}$i --file_prediction=${WORKING_DIR}${TAGGING_FILE}$i.pred --logtostderr
done

cat ${WORKING_DIR}${TAGGING_FILE}1.pred ${WORKING_DIR}${TAGGING_FILE}2.pred ${WORKING_DIR}${TAGGING_FILE}3.pred ${WORKING_DIR}${TAGGING_FILE}4.pred ${WORKING_DIR}${TAGGING_FILE}5.pred ${WORKING_DIR}${TAGGING_FILE}6.pred ${WORKING_DIR}${TAGGING_FILE}7.pred ${WORKING_DIR}${TAGGING_FILE}8.pred ${WORKING_DIR}${TAGGING_FILE}9.pred ${WORKING_DIR}${TAGGING_FILE}10.pred > ${WORKING_DIR}${TAGGING_FILE}.jack
python /home/lingpenk/research/scripts/TagConllUsingTBT.py ${TAGGING_ROOT}${CONLL_FILE} ${WORKING_DIR}${TAGGING_FILE}.jack Y > ${TAGGING_ROOT}${CONLL_FILE}.jack